### ISSUE TITLE
Linked List adding an item at specific index is not working properly

### ISSUE THREAD

**Issue by JainTarunJain** [ashish-chopra/Structures#30]
Issue is whenever i am adding an item in Linked List at specific index, item will not at that specific index.

**Comment by JoshVandeWalle** [comment]
Are the indexes zero based or one based?

**Comment by JainTarunJain** [comment]
indexes are 1 based, but the problem is when i want to add any item on any index then my pointer is also at same, it should be before that index.

**Comment by ashish-chopra** [comment]
Make sure to link the class file path in the issue/comments for easy access, guys! For this time, i am doing here: https://github.com/ashish-chopra/Structures/blob/master/src/main/java/com/lists/LinkedList.java

**Comment by JoshVandeWalle** [comment]
I think it is the for loop in LinkedList.add(Item,int) it iterates once too many times. Also am I not supposed to be able to use add by index to an empty list or the end? because doing so gets IndexOutBoundsException in all cases, since the check is if (index <= 0 || index > size()) and N starts at 0.

**Comment by ashish-chopra** [comment]
Correction merged in pull request #32 . Thanks tarun!
